credentials:
  usernames:
    jsmith:
      email: jsmith@gmail.com
      name: John Smith
      password: '$2b$12$.fReYMYmQnJIuItMK6BxheV4ZzguPToLv3m38iPwwG.SDepaTgZi.' # To be replaced
    rdoe:
      email: rdoe@gmail.com
      name: Rebecca Doe
      password: '$2b$12$VOLSYMakYuZnHFIDREluVOOdTtWgvFHpKYj9z7.ytR6ZU8WSpEdZG' # To be replaced
cookie:
  expiry_days: 30
  key: some_signature_key # can be any random string
  name: some_cookie_name
