credentials:
  usernames:
    jsmith:
      email: jsmith@gmail.com
      name: John Smith
      password: 'REPLACE_WITH_HASHED_PASSWORD_1' # To be replaced
    rdoe:
      email: rdoe@gmail.com
      name: Rebecca Doe
      password: 'REPLACE_WITH_HASHED_PASSWORD_2' # To be replaced
cookie:
  expiry_days: 30
  key: some_signature_key # can be any random string
  name: some_cookie_name
